# Generated by Django 5.0.5 on 2024-05-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
    ]
